version: "0.1"

namespace: myworld_b2c_dev
tag: 'dev'

environment: docker.dev
image:
    tag: spryker/php:7.3-alpine3.12
    environment:
        SPRYKER_CLUSTER: "cluster-2"
        SPRYKER_DEFAULT_STORE: "IT"
        SPRYKER_ACTIVE_STORES: "IT,PT"
    php:
        ini:
            "post_max_size": 600m
            "upload_max_filesize": 600m
            "memory_limit": 3000M
            "opcache.enable_cli": 0
            "opcache.enable": 1
            "apc.enable_cli": 1
        enabled-extensions:
            - blackfire
composer:
    mode: ''
    autoload: ''
assets:
    mode: development

regions:
    cluster-2:
        services:
            database:
                database: cluster-2-docker
                username: spryker
                password: secret

        stores:
            IT:
                services:
                    broker:
                        namespace: it-docker
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: it_search
            PT:
                services:
                    broker:
                        namespace: pt-docker
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: pt_search
groups:
    cluster-2:
        region: cluster-2
        applications:
            yves_eu:
                application: yves
                endpoints:
                    yves.it.myworld.local:
                        store: IT
                        services:
                            session:
                                namespace: 1
                    yves.pt.myworld.local:
                        store: PT
                        services:
                            session:
                                namespace: 2
            glue_eu:
                application: glue
                endpoints:
                    glue.it.myworld.local:
                        store: IT
                    glue.pt.myworld.local:
                        store: PT
            zed_eu:
                application: zed
                http:
                    max-request-body-size: 1600m
                endpoints:
                    zed.it.myworld.local:
                        store: IT
                        services:
                            session:
                                namespace: 3
                    zed.pt.myworld.local:
                        store: PT
                        services:
                            session:
                                namespace: 3
services:
    database:
        engine: mysql
        version: mariadb-10.5
        root:
            username: "root"
            password: "secret"
        endpoints:
            localhost:3306:
                protocol: tcp
    broker:
        engine: rabbitmq
        api:
            username: "spryker"
            password: "secret"
        endpoints:
            queue.myworld.local:
            localhost:5672:
                protocol: tcp
    session:
        engine: redis
    key_value_store:
        engine: redis
        endpoints:
            localhost:16379:
                protocol: tcp
    search:
        engine: elastic
        version: 6.8
        endpoints:
            localhost:9200:
                protocol: tcp
    scheduler:
        engine: jenkins
        endpoints:
            scheduler.myworld.local:
    mail_catcher:
        engine: mailhog
        endpoints:
            mail.myworld.local:
    swagger:
        engine: swagger-ui
        endpoints:
            swagger.myworld.local:
    redis-gui:
        engine: redis-commander
        endpoints:
            redis-commander.myworld.local:
    dashboard:
        engine: dashboard
        endpoints:
            spryker.local:
    webdriver:
        engine: chromedriver

docker:

    ssl:
        enabled: true
        redirect: true

    testing:
        store: IT

    debug:
        enabled: true
        xdebug:
            enabled: true

    mount:
        native:
            platforms:
                - linux

        mutagen:
            platforms:
                - macos

        docker-sync:
            platforms:
                - windows
