version: "0.1"

namespace: myworld_b2c_dev
tag: 'dev'

environment: docker.dev
image:
    tag: spryker/php:7.3-alpine3.12
    environment:
        SPRYKER_CLUSTER: "balkan-south"
        SPRYKER_DEFAULT_STORE: "BG"
        SPRYKER_ACTIVE_STORES: "BG,MK,AL,XK"
    php:
        ini:
            "post_max_size": 600m
            "upload_max_filesize": 600m
            "memory_limit": 3000M
            "opcache.enable_cli": 0
            "opcache.enable": 1
            "apc.enable_cli": 1
        enabled-extensions:
            - blackfire
composer:
    mode: ''
    autoload: ''
assets:
    mode: development

regions:
    balkan-south:
        services:
            database:
                database: balkan-south-docker
                username: spryker
                password: secret

        stores:
            MK:
                services:
                    broker:
                        namespace: mk-docker
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: mk_search
            BG:
                services:
                    broker:
                        namespace: bg-docker
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: bg_search
            AL:
                services:
                    broker:
                        namespace: al-docker
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: al_search
            XK:
                services:
                    broker:
                        namespace: xk-docker
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: xk_search
groups:
    balkan-south:
        region: balkan-south
        applications:
            yves_eu:
                application: yves
                endpoints:
                    yves.mk.myworld.local:
                        store: MK
                        services:
                            session:
                                namespace: 1
                    yves.bg.myworld.local:
                        store: BG
                        services:
                            session:
                                namespace: 2
                    yves.al.myworld.local:
                        store: AL
                        services:
                            session:
                                namespace: 3
                    yves.xk.myworld.local:
                        store: XK
                        services:
                            session:
                                namespace: 4
            glue_eu:
                application: glue
                endpoints:
                    glue.mk.myworld.local:
                        store: MK
                    glue.bg.myworld.local:
                        store: BG
                    glue.al.myworld.local:
                        store: AL
                    glue.xk.myworld.local:
                        store: XK
            zed_eu:
                application: zed
                http:
                    max-request-body-size: 1600m
                endpoints:
                    zed.mk.myworld.local:
                        store: MK
                        services:
                            session:
                                namespace: 5
                    zed.bg.myworld.local:
                        store: BG
                        services:
                            session:
                                namespace: 5
                    zed.al.myworld.local:
                        store: AL
                        services:
                            session:
                                namespace: 5
                    zed.xk.myworld.local:
                        store: XK
                        services:
                            session:
                                namespace: 5
services:
    database:
        engine: mysql
        version: mariadb-10.5
        root:
            username: "root"
            password: "secret"
        endpoints:
            localhost:3306:
                protocol: tcp
    broker:
        engine: rabbitmq
        api:
            username: "spryker"
            password: "secret"
        endpoints:
            queue.myworld.local:
            localhost:5672:
                protocol: tcp
    session:
        engine: redis
    key_value_store:
        engine: redis
        endpoints:
            localhost:16379:
                protocol: tcp
    search:
        engine: elastic
        version: 6.8
        endpoints:
            localhost:9200:
                protocol: tcp
    scheduler:
        engine: jenkins
        endpoints:
            scheduler.myworld.local:
    mail_catcher:
        engine: mailhog
        endpoints:
            mail.myworld.local:
    swagger:
        engine: swagger-ui
        endpoints:
            swagger.myworld.local:
    redis-gui:
        engine: redis-commander
        endpoints:
            redis-commander.myworld.local:
    dashboard:
        engine: dashboard
        endpoints:
            spryker.local:
    webdriver:
        engine: chromedriver

docker:

    ssl:
        enabled: true
        redirect: true

    testing:
        store: BG

    debug:
        enabled: true
        xdebug:
            enabled: true

    mount:
        native:
            platforms:
                - linux

        mutagen:
            platforms:
                - macos

        docker-sync:
            platforms:
                - windows
