version: "0.1"

namespace: myworld_b2c_dev
tag: 'dev'

environment: docker.dev
image:
    tag: spryker/php:7.3-alpine3.12
    environment:
        SPRYKER_CLUSTER: "baltic"
        SPRYKER_DEFAULT_STORE: "EE"
        SPRYKER_ACTIVE_STORES: "EE,LV,LT"
    php:
        ini:
            "post_max_size": 600m
            "upload_max_filesize": 600m
            "memory_limit": 3000M
            "opcache.enable_cli": 0
            "opcache.enable": 1
            "apc.enable_cli": 1
        enabled-extensions:
            - blackfire
composer:
    mode: ''
    autoload: ''
assets:
    mode: development

regions:
    baltic:
        services:
            database:
                database: baltic-docker
                username: spryker
                password: secret

        stores:
            EE:
                services:
                    broker:
                        namespace: ee-docker
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: ee_search
            LV:
                services:
                    broker:
                        namespace: lv-docker
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: lv_search
            LT:
                services:
                    broker:
                        namespace: lt-docker
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: lt_search
groups:
    baltic:
        region: baltic
        applications:
            yves_eu:
                application: yves
                endpoints:
                    yves.ee.myworld.local:
                        store: EE
                        services:
                            session:
                                namespace: 1
                    yves.lv.myworld.local:
                        store: LV
                        services:
                            session:
                                namespace: 2
                    yves.lt.myworld.local:
                        store: LT
                        services:
                            session:
                                namespace: 3
            glue_eu:
                application: glue
                endpoints:
                    glue.ee.myworld.local:
                        store: EE
                    glue.lv.myworld.local:
                        store: LV
                    glue.lt.myworld.local:
                        store: LT
            zed_eu:
                application: zed
                http:
                    max-request-body-size: 1600m
                endpoints:
                    zed.ee.myworld.local:
                        store: EE
                        services:
                            session:
                                namespace: 4
                    zed.lv.myworld.local:
                        store: LV
                        services:
                            session:
                                namespace: 4
                    zed.lt.myworld.local:
                        store: LT
                        services:
                            session:
                                namespace: 4
services:
    database:
        engine: mysql
        version: mariadb-10.5
        root:
            username: "root"
            password: "secret"
        endpoints:
            localhost:3306:
                protocol: tcp
    broker:
        engine: rabbitmq
        api:
            username: "spryker"
            password: "secret"
        endpoints:
            queue.myworld.local:
            localhost:5672:
                protocol: tcp
    session:
        engine: redis
    key_value_store:
        engine: redis
        endpoints:
            localhost:16379:
                protocol: tcp
    search:
        engine: elastic
        version: 6.8
        endpoints:
            localhost:9200:
                protocol: tcp
    scheduler:
        engine: jenkins
        endpoints:
            scheduler.myworld.local:
    mail_catcher:
        engine: mailhog
        endpoints:
            mail.myworld.local:
    swagger:
        engine: swagger-ui
        endpoints:
            swagger.myworld.local:
    redis-gui:
        engine: redis-commander
        endpoints:
            redis-commander.myworld.local:
    dashboard:
        engine: dashboard
        endpoints:
            spryker.local:
    webdriver:
        engine: chromedriver

docker:

    ssl:
        enabled: true
        redirect: true

    testing:
        store: EE

    debug:
        enabled: true
        xdebug:
            enabled: true

    mount:
        native:
            platforms:
                - linux

        mutagen:
            platforms:
                - macos

        docker-sync:
            platforms:
                - windows
