version: "0.1"

namespace: myworld_b2c_dev
tag: 'dev'

environment: docker.dev
image:
    tag: spryker/php:7.3-alpine3.12
    environment:
        SPRYKER_CLUSTER: "baltic-2"
        SPRYKER_DEFAULT_STORE: "BY"
        SPRYKER_ACTIVE_STORES: "BY,UA,RU"
    php:
        ini:
            "post_max_size": 600m
            "upload_max_filesize": 600m
            "memory_limit": 3000M
            "opcache.enable_cli": 0
            "opcache.enable": 1
            "apc.enable_cli": 1
        enabled-extensions:
            - blackfire
composer:
    mode: ''
    autoload: ''
assets:
    mode: development

regions:
    baltic-2:
        services:
            database:
                database: baltic-2-docker
                username: spryker
                password: secret

        stores:
            BY:
                services:
                    broker:
                        namespace: by-docker
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: by_search
            UA:
                services:
                    broker:
                        namespace: ua-docker
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: ua_search
            RU:
                services:
                    broker:
                        namespace: ru-docker
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: ru_search
groups:
    baltic-2:
        region: baltic-2
        applications:
            yves_eu:
                application: yves
                endpoints:
                    yves.by.myworld.local:
                        store: BY
                        services:
                            session:
                                namespace: 1
                    yves.ua.myworld.local:
                        store: UA
                        services:
                            session:
                                namespace: 2
                    yves.ru.myworld.local:
                        store: RU
                        services:
                            session:
                                namespace: 3
            glue_eu:
                application: glue
                endpoints:
                    glue.by.myworld.local:
                        store: BY
                    glue.ua.myworld.local:
                        store: UA
                    glue.ru.myworld.local:
                        store: RU
            zed_eu:
                application: zed
                http:
                    max-request-body-size: 1600m
                endpoints:
                    zed.by.myworld.local:
                        store: BY
                        services:
                            session:
                                namespace: 4
                    zed.ua.myworld.local:
                        store: UA
                        services:
                            session:
                                namespace: 4
                    zed.ru.myworld.local:
                        store: RU
                        services:
                            session:
                                namespace: 4
services:
    database:
        engine: mysql
        version: mariadb-10.5
        root:
            username: "root"
            password: "secret"
        endpoints:
            localhost:3306:
                protocol: tcp
    broker:
        engine: rabbitmq
        api:
            username: "spryker"
            password: "secret"
        endpoints:
            queue.myworld.local:
            localhost:5672:
                protocol: tcp
    session:
        engine: redis
    key_value_store:
        engine: redis
        endpoints:
            localhost:16379:
                protocol: tcp
    search:
        engine: elastic
        version: 6.8
        endpoints:
            localhost:9200:
                protocol: tcp
    scheduler:
        engine: jenkins
        endpoints:
            scheduler.myworld.local:
    mail_catcher:
        engine: mailhog
        endpoints:
            mail.myworld.local:
    swagger:
        engine: swagger-ui
        endpoints:
            swagger.myworld.local:
    redis-gui:
        engine: redis-commander
        endpoints:
            redis-commander.myworld.local:
    dashboard:
        engine: dashboard
        endpoints:
            spryker.local:
    webdriver:
        engine: chromedriver

docker:

    ssl:
        enabled: true
        redirect: true

    testing:
        store: BY

    debug:
        enabled: true
        xdebug:
            enabled: true

    mount:
        native:
            platforms:
                - linux

        mutagen:
            platforms:
                - macos

        docker-sync:
            platforms:
                - windows
