version: "0.1"

namespace: myworld_b2c_dev
tag: 'dev'

environment: docker.dev
image:
    tag: spryker/php:7.3-alpine3.12
    environment:
        SPRYKER_CLUSTER: "north"
        SPRYKER_DEFAULT_STORE: "NO"
        SPRYKER_ACTIVE_STORES: "NO,FI,DK,SE"
    php:
        ini:
            "post_max_size": 600m
            "upload_max_filesize": 600m
            "memory_limit": 3000M
            "opcache.enable_cli": 0
            "opcache.enable": 1
            "apc.enable_cli": 1
        enabled-extensions:
            - blackfire
composer:
    mode: ''
    autoload: ''
assets:
    mode: development

regions:
    north:
        services:
            database:
                database: north-docker
                username: spryker
                password: secret

        stores:
            FI:
                services:
                    broker:
                        namespace: fi-docker
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: fi_search
            NO:
                services:
                    broker:
                        namespace: no-docker
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: no_search
            DK:
                services:
                    broker:
                        namespace: dk-docker
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: dk_search
            SE:
                services:
                    broker:
                        namespace: se-docker
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: se_search
groups:
    north:
        region: north
        applications:
            yves_eu:
                application: yves
                endpoints:
                    yves.fi.myworld.local:
                        store: FI
                        services:
                            session:
                                namespace: 1
                    yves.no.myworld.local:
                        store: NO
                        services:
                            session:
                                namespace: 2
                    yves.dk.myworld.local:
                        store: DK
                        services:
                            session:
                                namespace: 3
                    yves.se.myworld.local:
                        store: SE
                        services:
                            session:
                                namespace: 4
            glue_eu:
                application: glue
                endpoints:
                    glue.fi.myworld.local:
                        store: FI
                    glue.no.myworld.local:
                        store: NO
                    glue.dk.myworld.local:
                        store: DK
                    glue.se.myworld.local:
                        store: SE
            zed_eu:
                application: zed
                http:
                    max-request-body-size: 1600m
                endpoints:
                    zed.fi.myworld.local:
                        store: FI
                        services:
                            session:
                                namespace: 5
                    zed.no.myworld.local:
                        store: NO
                        services:
                            session:
                                namespace: 5
                    zed.dk.myworld.local:
                        store: DK
                        services:
                            session:
                                namespace: 5
                    zed.se.myworld.local:
                        store: SE
                        services:
                            session:
                                namespace: 5
services:
    database:
        engine: mysql
        version: mariadb-10.5
        root:
            username: "root"
            password: "secret"
        endpoints:
            localhost:3306:
                protocol: tcp
    broker:
        engine: rabbitmq
        api:
            username: "spryker"
            password: "secret"
        endpoints:
            queue.myworld.local:
            localhost:5672:
                protocol: tcp
    session:
        engine: redis
    key_value_store:
        engine: redis
        endpoints:
            localhost:16379:
                protocol: tcp
    search:
        engine: elastic
        version: 6.8
        endpoints:
            localhost:9200:
                protocol: tcp
    scheduler:
        engine: jenkins
        endpoints:
            scheduler.myworld.local:
    mail_catcher:
        engine: mailhog
        endpoints:
            mail.myworld.local:
    swagger:
        engine: swagger-ui
        endpoints:
            swagger.myworld.local:
    redis-gui:
        engine: redis-commander
        endpoints:
            redis-commander.myworld.local:
    dashboard:
        engine: dashboard
        endpoints:
            spryker.local:
    webdriver:
        engine: chromedriver

docker:

    ssl:
        enabled: true
        redirect: true

    testing:
        store: NO

    debug:
        enabled: true
        xdebug:
            enabled: true

    mount:
        native:
            platforms:
                - linux

        mutagen:
            platforms:
                - macos

        docker-sync:
            platforms:
                - windows
