version: "0.1"

x-real-ip: &real-ip
    real-ip:
        from:
            - 10.0.0.0/8 # AWS VPC network
            - 103.21.244.0/22 # Cloudflare
            - 103.22.200.0/22 # Cloudflare
            - 103.31.4.0/22 # Cloudflare
            - 104.16.0.0/12 # Cloudflare
            - 108.162.192.0/18 # Cloudflare
            - 131.0.72.0/22 # Cloudflare
            - 141.101.64.0/18 # Cloudflare
            - 162.158.0.0/15 # Cloudflare
            - 172.64.0.0/13 # Cloudflare
            - 173.245.48.0/20 # Cloudflare
            - 188.114.96.0/20 # Cloudflare
            - 190.93.240.0/20 # Cloudflare
            - 197.234.240.0/22 # Cloudflare
            - 198.41.128.0/17 # Cloudflare
            - 2400:cb00::/32 # Cloudflare
            - 2606:4700::/32 # Cloudflare
            - 2803:f800::/32 # Cloudflare
            - 2405:b500::/32 # Cloudflare
            - 2405:8100::/32 # Cloudflare
            - 2c0f:f248::/32 # Cloudflare
            - 2a06:98c0::/29 # Cloudflare

x-frontend-auth: &frontend-auth
    <<: *real-ip
    auth:
        engine: basic
        users:
            -   username: myworld
                password: cloudgolive
        exclude:
            - '${ALLOWED_IP}' # AWS gateway
            - 185.60.20.0/24 # PayOne

x-backend-auth: &backend-auth
    <<: *real-ip
    auth:
        engine: basic
        users:
            -   username: myworldadmin
                password: cloudadmin
        exclude:
            - '${ALLOWED_IP}' # AWS gateway
            - 185.60.20.0/24 # PayOne


namespace: spryker-cloud
tag: '1.0'

environment: docker.prod
image:
    tag: spryker/php:7.3-alpine3.12
    environment:
        SPRYKER_CLUSTER: "baltic"
        SPRYKER_DEFAULT_STORE: "EE"
        SPRYKER_ACTIVE_STORES: "EE,LV,LT"
        SPRYKER_HOOK_BEFORE_DEPLOY: "vendor/bin/install -r baltic/pre-deploy -vvv"
        SPRYKER_HOOK_AFTER_DEPLOY: "true"
        SPRYKER_HOOK_INSTALL: "vendor/bin/install -r baltic/production --no-ansi -vvv"
        SPRYKER_HOOK_DESTRUCTIVE_INSTALL: "vendor/bin/install -r baltic/destructive --no-ansi -vvv"
        WEB_PROPERTY_ID: "GTM-53PNLT9"
    php:
        ini:
            "post_max_size": 1024M
            "upload_max_filesize": 1024M
            "memory_limit": 3000M
        enabled-extensions:
            - blackfire
            - newrelic

composer:
    mode: --no-dev
    autoload: --classmap-authoritative

assets:
    image: fholzer/nginx-brotli:v1.18.0
    mode: production
    compression:
        brotli:
            static: only
        gzip:
            static: true
            level: 5

regions:
    baltic:
        services:
            mail:
                sender:
                    name: myWorld-No-Reply
                    email: noreply@marketplace.myworld.com
            database:
                database: myworld_prod_baltic
                username: spryker
                password: secret

        stores:
            EE:
                services:
                    broker:
                        namespace: ee_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: ee_search
                    session:
                        namespace: 2
            LV:
                services:
                    broker:
                        namespace: lv_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: lv_search
                    session:
                        namespace: 2
            LT:
                services:
                    broker:
                        namespace: lt_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: lt_search
                    session:
                        namespace: 2

groups:
    baltic:
        region: baltic
        applications:
            Redirects:
                application: static
                endpoints:
                    ee.products.myworld.com:
                        store: EE
                        redirect:
                            type: 302
                            url: www.ee.products.myworld.com
                    lv.products.myworld.com:
                        store: LV
                        redirect:
                            type: 302
                            url: www.lv.products.myworld.com
                    lt.products.myworld.com:
                        store: LT
                        redirect:
                            type: 302
                            url: www.lt.products.myworld.com
            Yves:
                application: yves
                endpoints:
                    www.ee.products.myworld.com:
                        store: EE
                    www.lv.products.myworld.com:
                        store: LV
                    www.lt.products.myworld.com:
                        store: LT
            Zed:
                application: zed
                http:
                    max-request-body-size: 1600m
                endpoints:
                    zed.ee.products.myworld.com:
                        store: EE
                        <<: *backend-auth
                    zed.lv.products.myworld.com:
                        store: LV
                        <<: *backend-auth
                    zed.lt.products.myworld.com:
                        store: LT
                        <<: *backend-auth
            Glue:
                application: glue
                endpoints:
                    glue.ee.products.myworld.com:
                        store: EE
                    glue.lv.products.myworld.com:
                        store: LV
                    glue.lt.products.myworld.com:
                        store: LT
services:
    database:
        engine: mysql
        version: mariadb-10.5
        root:
            username: "root"
            password: "secret"
        endpoints:
            localhost:3306:
                protocol: tcp
    broker:
        engine: rabbitmq
        api:
            username: "spryker"
            password: "secret"
        endpoints:
            rabbitmq.baltic.products.myworld.coms:
            localhost:5672:
                protocol: tcp
    session:
        engine: redis
    key_value_store:
        engine: redis
        endpoints:
            localhost:16379:
                protocol: tcp
    search:
        engine: elastic
        version: 6.8
        endpoints:
            localhost:9200:
                protocol: tcp
    scheduler:
        engine: jenkins
        endpoints:
            jenkins.baltic.products.myworld.coms:
    mail_catcher:
        engine: mailhog
        endpoints:
            mail.baltic.products.myworld.coms:

docker:

    blackfire:
        enabled: true

    ssl:
        enabled: true
        redirect: true

    debug:
        enabled: false
        xdebug:
            enabled: false

    testing:
        store: EE

    mount:
        baked:
