version: "0.1"

x-real-ip: &real-ip
    real-ip:
        from:
            - 10.0.0.0/8 # AWS VPC network
            - 103.21.244.0/22 # Cloudflare
            - 103.22.200.0/22 # Cloudflare
            - 103.31.4.0/22 # Cloudflare
            - 104.16.0.0/12 # Cloudflare
            - 108.162.192.0/18 # Cloudflare
            - 131.0.72.0/22 # Cloudflare
            - 141.101.64.0/18 # Cloudflare
            - 162.158.0.0/15 # Cloudflare
            - 172.64.0.0/13 # Cloudflare
            - 173.245.48.0/20 # Cloudflare
            - 188.114.96.0/20 # Cloudflare
            - 190.93.240.0/20 # Cloudflare
            - 197.234.240.0/22 # Cloudflare
            - 198.41.128.0/17 # Cloudflare
            - 2400:cb00::/32 # Cloudflare
            - 2606:4700::/32 # Cloudflare
            - 2803:f800::/32 # Cloudflare
            - 2405:b500::/32 # Cloudflare
            - 2405:8100::/32 # Cloudflare
            - 2c0f:f248::/32 # Cloudflare
            - 2a06:98c0::/29 # Cloudflare

x-frontend-auth: &frontend-auth
    <<: *real-ip
    auth:
        engine: basic
        users:
            -   username: myworld
                password: cloudgolive
        exclude:
            - '${ALLOWED_IP}' # AWS gateway
            - 185.60.20.0/24 # PayOne

x-backend-auth: &backend-auth
    <<: *real-ip
    auth:
        engine: basic
        users:
            -   username: myworldadmin
                password: cloudadmin
        exclude:
            - '${ALLOWED_IP}' # AWS gateway
            - 185.60.20.0/24 # PayOne


namespace: spryker-cloud
tag: '1.0'

environment: docker.prod
image:
    tag: spryker/php:7.3-alpine3.12
    environment:
        SPRYKER_CLUSTER: "west"
        SPRYKER_DEFAULT_STORE: "GB"
        SPRYKER_ACTIVE_STORES: "GB,BE,IE,NL"
        SPRYKER_HOOK_BEFORE_DEPLOY: "vendor/bin/install -r west/pre-deploy -vvv"
        SPRYKER_HOOK_AFTER_DEPLOY: "true"
        SPRYKER_HOOK_INSTALL: "vendor/bin/install -r west/production --no-ansi -vvv"
        SPRYKER_HOOK_DESTRUCTIVE_INSTALL: "vendor/bin/install -r west/destructive --no-ansi -vvv"
        WEB_PROPERTY_ID: "GTM-53PNGR9"
    php:
        ini:
            "post_max_size": 1024M
            "upload_max_filesize": 1024M
            "memory_limit": 3000M
        enabled-extensions:
            - blackfire
            - newrelic

composer:
    mode: --no-dev
    autoload: --classmap-authoritative

assets:
    image: fholzer/nginx-brotli:v1.18.0
    mode: production
    compression:
        brotli:
            static: only
        gzip:
            static: true
            level: 5

regions:
    west:
        services:
            mail:
                sender:
                    name: myWorld-No-Reply
                    email: noreply@marketplace.myworld.com
            database:
                database: myworld_prod_west
                username: spryker
                password: secret

        stores:
            GB:
                services:
                    broker:
                        namespace: gb_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: gb_search
                    session:
                        namespace: 2
            BE:
                services:
                    broker:
                        namespace: be_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: be_search
                    session:
                        namespace: 2
            IE:
                services:
                    broker:
                        namespace: ie_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: ie_search
                    session:
                        namespace: 2
            NL:
                services:
                    broker:
                        namespace: nl_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: nl_search
                    session:
                        namespace: 2

groups:
    west:
        region: west
        applications:
            Redirects:
                application: static
                endpoints:
                    gb.marketplace.myworld.com:
                        store: GB
                        redirect:
                            type: 302
                            url: www.gb.marketplace.myworld.com
                    be.marketplace.myworld.com:
                        store: BE
                        redirect:
                            type: 302
                            url: www.be.marketplace.myworld.com
                    ie.marketplace.myworld.com:
                        store: IE
                        redirect:
                            type: 302
                            url: www.ie.marketplace.myworld.com
                    nl.marketplace.myworld.com:
                        store: NL
                        redirect:
                            type: 302
                            url: www.nl.marketplace.myworld.com
            Yves:
                application: yves
                endpoints:
                    www.gb.marketplace.myworld.com:
                        store: GB
                    www.be.marketplace.myworld.com:
                        store: BE
                    www.ie.marketplace.myworld.com:
                        store: IE
                    www.nl.marketplace.myworld.com:
                        store: NL
            Zed:
                application: zed
                http:
                    max-request-body-size: 1600m
                endpoints:
                    zed.gb.marketplace.myworld.com:
                        store: GB
                        <<: *backend-auth
                    zed.be.marketplace.myworld.com:
                        store: BE
                        <<: *backend-auth
                    zed.ie.marketplace.myworld.com:
                        store: IE
                        <<: *backend-auth
                    zed.nl.marketplace.myworld.com:
                        store: NL
                        <<: *backend-auth
            Glue:
                application: glue
                endpoints:
                    glue.gb.marketplace.myworld.com:
                        store: GB
                    glue.be.marketplace.myworld.com:
                        store: BE
                    glue.ie.marketplace.myworld.com:
                        store: IE
                    glue.nl.marketplace.myworld.com:
                        store: NL

services:
    database:
        engine: mysql
        version: mariadb-10.5
        root:
            username: "root"
            password: "secret"
        endpoints:
            localhost:3306:
                protocol: tcp
    broker:
        engine: rabbitmq
        api:
            username: "spryker"
            password: "secret"
        endpoints:
            rabbitmq.west.marketplace.myworld.com:
            localhost:5672:
                protocol: tcp
    session:
        engine: redis
    key_value_store:
        engine: redis
        endpoints:
            localhost:16379:
                protocol: tcp
    search:
        engine: elastic
        version: 6.8
        endpoints:
            localhost:9200:
                protocol: tcp
    scheduler:
        engine: jenkins
        endpoints:
            jenkins.west.marketplace.myworld.com:

docker:

    blackfire:
        enabled: true

    ssl:
        enabled: true
        redirect: true

    debug:
        enabled: false
        xdebug:
            enabled: false

    testing:
        store: GB

    mount:
        baked:
