version: "0.1"

x-real-ip: &real-ip
    real-ip:
        from:
            - 10.0.0.0/8 # AWS VPC network
            - 103.21.244.0/22 # Cloudflare
            - 103.22.200.0/22 # Cloudflare
            - 103.31.4.0/22 # Cloudflare
            - 104.16.0.0/12 # Cloudflare
            - 108.162.192.0/18 # Cloudflare
            - 131.0.72.0/22 # Cloudflare
            - 141.101.64.0/18 # Cloudflare
            - 162.158.0.0/15 # Cloudflare
            - 172.64.0.0/13 # Cloudflare
            - 173.245.48.0/20 # Cloudflare
            - 188.114.96.0/20 # Cloudflare
            - 190.93.240.0/20 # Cloudflare
            - 197.234.240.0/22 # Cloudflare
            - 198.41.128.0/17 # Cloudflare
            - 2400:cb00::/32 # Cloudflare
            - 2606:4700::/32 # Cloudflare
            - 2803:f800::/32 # Cloudflare
            - 2405:b500::/32 # Cloudflare
            - 2405:8100::/32 # Cloudflare
            - 2c0f:f248::/32 # Cloudflare
            - 2a06:98c0::/29 # Cloudflare

x-frontend-auth: &frontend-auth
    <<: *real-ip
    auth:
        engine: basic
        users:
            -   username: myworld
                password: cloudgolive
        exclude:
            - '${ALLOWED_IP}' # AWS gateway
            - 185.60.20.0/24 # PayOne

x-backend-auth: &backend-auth
    <<: *real-ip
    auth:
        engine: basic
        users:
            -   username: myworldadmin
                password: cloudadmin
        exclude:
            - '${ALLOWED_IP}' # AWS gateway
            - 185.60.20.0/24 # PayOne


namespace: spryker-cloud
tag: '1.0'

environment: docker.prod
image:
    tag: spryker/php:7.3-alpine3.12
    environment:
        SPRYKER_CLUSTER: "apac"
        SPRYKER_DEFAULT_STORE: "MY"
        SPRYKER_ACTIVE_STORES: "MY,HK,AU,NZ,PH,TH,MO"
        SPRYKER_HOOK_BEFORE_DEPLOY: "vendor/bin/install -r apac/pre-deploy -vvv"
        SPRYKER_HOOK_AFTER_DEPLOY: "true"
        SPRYKER_HOOK_INSTALL: "vendor/bin/install -r apac/production --no-ansi -vvv"
        SPRYKER_HOOK_DESTRUCTIVE_INSTALL: "vendor/bin/install -r apac/destructive --no-ansi -vvv"
        WEB_PROPERTY_ID: "GTM-53PNGR9"
    php:
        ini:
            "post_max_size": 1024M
            "upload_max_filesize": 1024M
            "memory_limit": 3000M
        enabled-extensions:
            - blackfire
            - newrelic

composer:
    mode: --no-dev
    autoload: --classmap-authoritative

assets:
    image: fholzer/nginx-brotli:v1.18.0
    mode: production
    compression:
        brotli:
            static: only
        gzip:
            static: true
            level: 5

regions:
    apac:
        services:
            mail:
                sender:
                    name: myWorld-No-Reply
                    email: noreply@marketplace.myworld.com
            database:
                database: myworld_prod_apac
                username: spryker
                password: secret

        stores:
            MY:
                services:
                    broker:
                        namespace: my_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: my_search
                    session:
                        namespace: 2
            HK:
                services:
                    broker:
                        namespace: hk_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: hk_search
                    session:
                        namespace: 2
            AU:
                services:
                    broker:
                        namespace: au_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: au_search
                    session:
                        namespace: 2
            NZ:
                services:
                    broker:
                        namespace: nz_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: nz_search
                    session:
                        namespace: 2
            PH:
                services:
                    broker:
                        namespace: ph_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: ph_search
                    session:
                        namespace: 2
            TH:
                services:
                    broker:
                        namespace: th_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: th_search
                    session:
                        namespace: 2
            MO:
                services:
                    broker:
                        namespace: mo_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: mo_search
                    session:
                        namespace: 2

groups:
    apac:
        region: apac
        applications:
            Redirects:
                application: static
                endpoints:
                    my.products.myworld.com:
                        store: MY
                        redirect:
                            type: 302
                            url: www.my.products.myworld.com
                    hk.products.myworld.com:
                        store: HK
                        redirect:
                            type: 302
                            url: www.hk.products.myworld.com
                    au.products.myworld.com:
                        store: AU
                        redirect:
                            type: 302
                            url: www.au.products.myworld.com
                    nz.products.myworld.com:
                        store: NZ
                        redirect:
                            type: 302
                            url: www.nz.products.myworld.com
                    ph.products.myworld.com:
                        store: PH
                        redirect:
                            type: 302
                            url: www.ph.products.myworld.com
                    th.products.myworld.com:
                        store: TH
                        redirect:
                            type: 302
                            url: www.th.products.myworld.com
                    mo.products.myworld.com:
                        store: MO
                        redirect:
                            type: 302
                            url: www.mo.products.myworld.com
            Yves:
                application: yves
                endpoints:
                    www.my.products.myworld.com:
                        store: MY
                    www.hk.products.myworld.com:
                        store: HK
                    www.au.products.myworld.com:
                        store: AU
                    www.nz.products.myworld.com:
                        store: NZ
                    www.ph.products.myworld.com:
                        store: PH
                    www.th.products.myworld.com:
                        store: TH
                    www.mo.products.myworld.com:
                        store: MO
            Zed:
                application: zed
                http:
                    max-request-body-size: 1600m
                endpoints:
                    zed.my.products.myworld.com:
                        store: MY
                        <<: *backend-auth
                    zed.hk.products.myworld.com:
                        store: HK
                        <<: *backend-auth
                    zed.au.products.myworld.com:
                        store: AU
                        <<: *backend-auth
                    zed.nz.products.myworld.com:
                        store: NZ
                        <<: *backend-auth
                    zed.ph.products.myworld.com:
                        store: PH
                        <<: *backend-auth
                    zed.th.products.myworld.com:
                        store: TH
                        <<: *backend-auth
                    zed.mo.products.myworld.com:
                        store: MO
                        <<: *backend-auth
            Glue:
                application: glue
                endpoints:
                    glue.my.products.myworld.com:
                        store: MY
                    glue.hk.products.myworld.com:
                        store: HK
                    glue.au.products.myworld.com:
                        store: AU
                    glue.nz.products.myworld.com:
                        store: NZ
                    glue.ph.products.myworld.com:
                        store: PH
                    glue.yh.products.myworld.com:
                        store: TH
                    glue.mo.products.myworld.com:
                        store: MO

services:
    database:
        engine: mysql
        version: mariadb-10.5
        root:
            username: "root"
            password: "secret"
        endpoints:
            localhost:3306:
                protocol: tcp
    broker:
        engine: rabbitmq
        api:
            username: "spryker"
            password: "secret"
        endpoints:
            rabbitmq.apac.products.myworld.coms:
            localhost:5672:
                protocol: tcp
    session:
        engine: redis
    key_value_store:
        engine: redis
        endpoints:
            localhost:16379:
                protocol: tcp
    search:
        engine: elastic
        version: 6.8
        endpoints:
            localhost:9200:
                protocol: tcp
    scheduler:
        engine: jenkins
        endpoints:
            jenkins.apac.products.myworld.coms:
    mail_catcher:
        engine: mailhog
        endpoints:
            mail.apac.products.myworld.coms:

docker:

    blackfire:
        enabled: true

    ssl:
        enabled: true
        redirect: true

    debug:
        enabled: false
        xdebug:
            enabled: false

    testing:
        store: MY

    mount:
        baked:
