version: "0.1"

x-real-ip: &real-ip
    real-ip:
        from:
            - 10.0.0.0/8 # AWS VPC network
            - 103.21.244.0/22 # Cloudflare
            - 103.22.200.0/22 # Cloudflare
            - 103.31.4.0/22 # Cloudflare
            - 104.16.0.0/12 # Cloudflare
            - 108.162.192.0/18 # Cloudflare
            - 131.0.72.0/22 # Cloudflare
            - 141.101.64.0/18 # Cloudflare
            - 162.158.0.0/15 # Cloudflare
            - 172.64.0.0/13 # Cloudflare
            - 173.245.48.0/20 # Cloudflare
            - 188.114.96.0/20 # Cloudflare
            - 190.93.240.0/20 # Cloudflare
            - 197.234.240.0/22 # Cloudflare
            - 198.41.128.0/17 # Cloudflare
            - 2400:cb00::/32 # Cloudflare
            - 2606:4700::/32 # Cloudflare
            - 2803:f800::/32 # Cloudflare
            - 2405:b500::/32 # Cloudflare
            - 2405:8100::/32 # Cloudflare
            - 2c0f:f248::/32 # Cloudflare
            - 2a06:98c0::/29 # Cloudflare

x-frontend-auth: &frontend-auth
    <<: *real-ip
    auth:
        engine: basic
        users:
            -   username: myworld
                password: cloudgolive
        exclude:
            - '${ALLOWED_IP}' # AWS gateway
            - 185.60.20.0/24 # PayOne

x-backend-auth: &backend-auth
    <<: *real-ip
    auth:
        engine: basic
        users:
            -   username: myworldadmin
                password: cloudadmin
        exclude:
            - '${ALLOWED_IP}' # AWS gateway
            - 185.60.20.0/24 # PayOne


namespace: spryker-cloud
tag: '1.0'

environment: docker.prod
image:
    tag: spryker/php:7.3-alpine3.12
    environment:
        SPRYKER_CLUSTER: "balkan-south"
        SPRYKER_DEFAULT_STORE: "BG"
        SPRYKER_ACTIVE_STORES: "BG,MK,AL,XK"
        SPRYKER_HOOK_BEFORE_DEPLOY: "vendor/bin/install -r balkan-south/pre-deploy -vvv"
        SPRYKER_HOOK_AFTER_DEPLOY: "true"
        SPRYKER_HOOK_INSTALL: "vendor/bin/install -r balkan-south/production --no-ansi -vvv"
        SPRYKER_HOOK_DESTRUCTIVE_INSTALL: "vendor/bin/install -r balkan-south/destructive --no-ansi -vvv"
        WEB_PROPERTY_ID: "GTM-53PNGR9"
    php:
        ini:
            "post_max_size": 1024M
            "upload_max_filesize": 1024M
            "memory_limit": 3000M
        enabled-extensions:
            - blackfire
            - newrelic

composer:
    mode: --no-dev
    autoload: --classmap-authoritative

assets:
    image: fholzer/nginx-brotli:v1.18.0
    mode: production
    compression:
        brotli:
            static: only
        gzip:
            static: true
            level: 5

regions:
    balkan-south:
        services:
            mail:
                sender:
                    name: myWorld-No-Reply
                    email: noreply@marketplace.myworld.com
            database:
                database: myworld_prod_balkan-south
                username: spryker
                password: secret

        stores:
            BG:
                services:
                    broker:
                        namespace: bg_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: bg_search
                    session:
                        namespace: 2
            MK:
                services:
                    broker:
                        namespace: mk_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: mk_search
                    session:
                        namespace: 2
            AL:
                services:
                    broker:
                        namespace: al_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: al_search
                    session:
                        namespace: 2
            XK:
                services:
                    broker:
                        namespace: xk_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: xk_search
                    session:
                        namespace: 2

groups:
    balkan-south:
        region: balkan-south
        applications:
            Redirects:
                application: static
                endpoints:
                    bg.products.myworld.com:
                        store: BG
                        redirect:
                            type: 302
                            url: www.bg.products.myworld.com
                    mk.products.myworld.com:
                        store: MK
                        redirect:
                            type: 302
                            url: www.mk.products.myworld.com
                    al.products.myworld.com:
                        store: AL
                        redirect:
                            type: 302
                            url: www.al.products.myworld.com
                    xk.products.myworld.com:
                        store: XK
                        redirect:
                            type: 302
                            url: www.xk.products.myworld.com
            Yves:
                application: yves
                endpoints:
                    www.bg.products.myworld.com:
                        store: BG
                    www.mk.products.myworld.com:
                        store: MK
                    www.al.products.myworld.com:
                        store: AL
                    www.xk.products.myworld.com:
                        store: XK
            Zed:
                application: zed
                http:
                    max-request-body-size: 1600m
                endpoints:
                    zed.bg.products.myworld.com:
                        store: BG
                        <<: *backend-auth
                    zed.mk.products.myworld.com:
                        store: MK
                        <<: *backend-auth
                    zed.al.products.myworld.com:
                        store: AL
                        <<: *backend-auth
                    zed.xk.products.myworld.com:
                        store: XK
                        <<: *backend-auth
            Glue:
                application: glue
                endpoints:
                    glue.bg.products.myworld.com:
                        store: BG
                    glue.mk.products.myworld.com:
                        store: MK
                    glue.al.products.myworld.com:
                        store: AL
                    glue.xk.products.myworld.com:
                        store: XK

services:
    database:
        engine: mysql
        version: mariadb-10.5
        root:
            username: "root"
            password: "secret"
        endpoints:
            localhost:3306:
                protocol: tcp
    broker:
        engine: rabbitmq
        api:
            username: "spryker"
            password: "secret"
        endpoints:
            rabbitmq.balkan-south.products.myworld.coms:
            localhost:5672:
                protocol: tcp
    session:
        engine: redis
    key_value_store:
        engine: redis
        endpoints:
            localhost:16379:
                protocol: tcp
    search:
        engine: elastic
        version: 6.8
        endpoints:
            localhost:9200:
                protocol: tcp
    scheduler:
        engine: jenkins
        endpoints:
            jenkins.balkan-south.products.myworld.coms:
    mail_catcher:
        engine: mailhog
        endpoints:
            mail.balkan-south.products.myworld.coms:

docker:

    blackfire:
        enabled: true

    ssl:
        enabled: true
        redirect: true

    debug:
        enabled: false
        xdebug:
            enabled: false

    testing:
        store: BG

    mount:
        baked:
