<?php

/**
 * This file is part of the Spryker Commerce OS.
 * For full license information, please view the LICENSE file that was distributed with this source code.
 */

namespace Pyz\Shared\MyWorldPayment;

interface MyWorldPaymentConstants
{
    public const FLOWS_DEFAULT_TYPE = 'MY_WORLD_PAYMENT_CONSTANTS:FLOWS_DEFAULT_TYPE';
    //Payment options names
    public const PAYMENT_NAME_E_VOUCHER = 'MY_WORLD_PAYMENT_CONSTANTS:PAYMENT_NAME_E_VOUCHER';
    public const PAYMENT_NAME_BENEFIT_VOUCHER = 'MY_WORLD_PAYMENT_CONSTANTS:PAYMENT_NAME_BENEFIT_VOUCHER';
    public const PAYMENT_NAME_BENEFIT_VOUCHER_ACCOUNT = 'MY_WORLD_PAYMENT_CONSTANTS:PAYMENT_NAME_BENEFIT_VOUCHER_ACCOUNT';
    // Payment options
    public const OPTION_EVOUCHER = 'MY_WORLD_PAYMENT_CONSTANTS:OPTION_EVOUCHER';
    public const OPTION_EVOUCHER_ON_BEHALF_OF_MARKETER = 'MY_WORLD_PAYMENT_CONSTANTS:OPTION_EVOUCHER_ON_BEHALF_OF_MARKETER';
    public const OPTION_CASHBACK_ACCOUNT = 'MY_WORLD_PAYMENT_CONSTANTS:OPTION_CASHBACK_ACCOUNT';
    public const OPTION_MVOUCHER_ACCOUNT = 'MY_WORLD_PAYMENT_CONSTANTS:OPTION_MVOUCHER_ACCOUNT';
    public const OPTION_SHOPPING_POINTS_ACCOUNT = 'MY_WORLD_PAYMENT_CONSTANTS:OPTION_SHOPPING_POINTS_ACCOUNT';
    public const OPTION_BENEFIT_VOUCHER_ACCOUNT = 'MY_WORLD_PAYMENT_CONSTANTS:OPTION_BENEFIT_VOUCHER_ACCOUNT';
    // Payment options names to options ids map
    public const OPTION_NAME_TO_ID_MAP = 'MY_WORLD_PAYMENT_CONSTANTS:OPTION_NAME_TO_ID_MAP';
    public const LIST_AVAILABLE_OPTIONS = 'MY_WORLD_PAYMENT_CONSTANTS:LIST_AVAILABLE_OPTIONS';
    public const UNIT_TYPE_TO_OPTION_MAP = 'MY_WORLD_PAYMENT_CONSTANTS:UNIT_TYPE_TO_OPTION_MAP';
    public const PAYMENT_NAME_TO_PAYMENT_ID_MAP = 'MY_WORLD_PAYMENT_CONSTANTS:PAYMENT_NAME_TO_PAYMENT_ID_MAP';
    // Unit Types
    public const UNIT_TYPE_CURRENCY = 'MY_WORLD_PAYMENT_CONSTANTS:UNIT_TYPE_CURRENCY';
    public const UNIT_TYPE_UNIT = 'MY_WORLD_PAYMENT_CONSTANTS:UNIT_TYPE_UNIT';
    // Attributes Keys
    public const PRODUCT_ATTRIBUTE_KEY_BENEFIT_STORE = 'MY_WORLD_PAYMENT_CONSTANTS:PRODUCT_ATTRIBUTE_KEY_BENEFIT_STORE';
    public const PRODUCT_ATTRIBUTE_KEY_BENEFIT_AMOUNT = 'MY_WORLD_PAYMENT_CONSTANTS:PRODUCT_ATTRIBUTE_KEY_BENEFIT_AMOUNT';
    public const PRODUCT_ATTRIBUTE_KEY_BENEFIT_STORE_SALES_PRICE = 'MY_WORLD_PAYMENT_CONSTANTS:PRODUCT_ATTRIBUTE_KEY_BENEFIT_STORE_SALES_PRICE';
    // Api response error codes
    public const RESPONSE_ERROR_CODE_GENERATION_NOT_CONFIGURED = 30;
}
