version: "0.1"

x-real-ip: &real-ip
    real-ip:
        from:
            - 10.0.0.0/8 # AWS VPC network
            - 103.21.244.0/22 # Cloudflare
            - 103.22.200.0/22 # Cloudflare
            - 103.31.4.0/22 # Cloudflare
            - 104.16.0.0/12 # Cloudflare
            - 108.162.192.0/18 # Cloudflare
            - 131.0.72.0/22 # Cloudflare
            - 141.101.64.0/18 # Cloudflare
            - 162.158.0.0/15 # Cloudflare
            - 172.64.0.0/13 # Cloudflare
            - 173.245.48.0/20 # Cloudflare
            - 188.114.96.0/20 # Cloudflare
            - 190.93.240.0/20 # Cloudflare
            - 197.234.240.0/22 # Cloudflare
            - 198.41.128.0/17 # Cloudflare
            - 2400:cb00::/32 # Cloudflare
            - 2606:4700::/32 # Cloudflare
            - 2803:f800::/32 # Cloudflare
            - 2405:b500::/32 # Cloudflare
            - 2405:8100::/32 # Cloudflare
            - 2c0f:f248::/32 # Cloudflare
            - 2a06:98c0::/29 # Cloudflare

x-frontend-auth: &frontend-auth
    <<: *real-ip
    auth:
        engine: basic
        users:
            -   username: cloud
                password: cloud
        exclude:
            - '${ALLOWED_IP}' # AWS gateway
            - 185.60.20.0/24 # PayOne

namespace: spryker-cloud
tag: '1.0'

environment: docker.demo
image:
    tag: spryker/php:7.3-alpine3.12
    environment:
        SPRYKER_CLUSTER: "america-2"
        SPRYKER_DEFAULT_STORE: "CA"
        SPRYKER_ACTIVE_STORES: "CA,BR,CO,MX"
        SPRYKER_HOOK_BEFORE_DEPLOY: "vendor/bin/install -r america-2/pre-deploy -vvv"
        SPRYKER_HOOK_AFTER_DEPLOY: "true"
        SPRYKER_HOOK_INSTALL: "vendor/bin/install -r america-2/production --no-ansi -vvv"
        SPRYKER_HOOK_DESTRUCTIVE_INSTALL: "vendor/bin/install -r america-2/destructive-stag --no-ansi -vvv"
        WEB_PROPERTY_ID: "GTM-53PNGR9"
    php:
        ini:
            "post_max_size": 1024M
            "upload_max_filesize": 1024M
            "opcache.enable_cli": 1
            "apc.enable_cli": 1
        enabled-extensions:
            - blackfire
            - newrelic

composer:
    mode: --no-dev
    autoload: --classmap-authoritative

assets:
    image: fholzer/nginx-brotli:v1.18.0
    mode: production
    compression:
        brotli:
            static: only
        gzip:
            static: true
            level: 5

regions:
    america-2:
        services:
            database:
                database: myworld_staging-america-2
                username: spryker
                password: secret

        stores:
            CA:
                services:
                    broker:
                        namespace: ca_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: ca_search
                    session:
                        namespace: 1
            BR:
                services:
                    broker:
                        namespace: br_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: br_search
                    session:
                        namespace: 1
            CO:
                services:
                    broker:
                        namespace: co_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: co_search
                    session:
                        namespace: 1
            MX:
                services:
                    broker:
                        namespace: mx_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: mx_search
                    session:
                        namespace: 1

groups:
    america-2:
        region: america-2
        applications:
            Redirects:
                application: static
                endpoints:
                    ca.myworld-mca.cloud.spryker.toys:
                        store: CA
                        redirect:
                            type: 302
                            url: www.ca.myworld-mca.cloud.spryker.toys
                    br.myworld-mca.cloud.spryker.toys:
                        store: BR
                        redirect:
                            type: 302
                            url: www.br.myworld-mca.cloud.spryker.toys
                    co.myworld-mca.cloud.spryker.toys:
                        store: CO
                        redirect:
                            type: 302
                            url: www.co.myworld-mca.cloud.spryker.toys
                    mx.myworld-mca.cloud.spryker.toys:
                        store: MX
                        redirect:
                            type: 302
                            url: www.mx.myworld-mca.cloud.spryker.toys
            Yves:
                application: yves
                endpoints:
                    www.ca.myworld-mca.cloud.spryker.toys:
                        store: CA
                        <<: *frontend-auth
                    www.br.myworld-mca.cloud.spryker.toys:
                        store: BR
                        <<: *frontend-auth
                    www.co.myworld-mca.cloud.spryker.toys:
                        store: CO
                        <<: *frontend-auth
                    www.mx.myworld-mca.cloud.spryker.toys:
                        store: MX
                        <<: *frontend-auth
            Zed:
                application: zed
                http:
                    max-request-body-size: 1600m
                endpoints:
                    zed.ca.myworld-mca.cloud.spryker.toys:
                        store: CA
                        <<: *frontend-auth
                    zed.br.myworld-mca.cloud.spryker.toys:
                        store: BR
                        <<: *frontend-auth
                    zed.co.myworld-mca.cloud.spryker.toys:
                        store: CO
                        <<: *frontend-auth
                    zed.mx.myworld-mca.cloud.spryker.toys:
                        store: MX
                        <<: *frontend-auth
            Glue:
                application: glue
                endpoints:
                    glue.ca.myworld-mca.cloud.spryker.toys:
                        store: CA
                    glue.br.myworld-mca.cloud.spryker.toys:
                        store: BR
                    glue.co.myworld-mca.cloud.spryker.toys:
                        store: CO
                    glue.mx.myworld-mca.cloud.spryker.toys:
                        store: MX

services:
    database:
        engine: mysql
        version: mariadb-10.5
        root:
            username: "root"
            password: "secret"
        endpoints:
            localhost:5432:
                protocol: tcp
    broker:
        engine: rabbitmq
        api:
            username: "spryker"
            password: "secret"
        endpoints:
            rabbitmq.myworld-mca-america-2.cloud.spryker.toys:
            localhost:5672:
                protocol: tcp
    session:
        engine: redis
    key_value_store:
        engine: redis
        endpoints:
            localhost:16379:
                protocol: tcp
    search:
        engine: elastic
        version: 6.8
        endpoints:
            localhost:9200:
                protocol: tcp
    scheduler:
        engine: jenkins
        endpoints:
            jenkins.myworld-mca-america-2.cloud.spryker.toys:
    mail_catcher:
        engine: mailhog
        endpoints:
            mail.myworld-mca-america-2.cloud.spryker.toys:

docker:

    blackfire:
        enabled: true

    ssl:
        enabled: true
        redirect: true

    debug:
        enabled: false
        xdebug:
            enabled: false

    testing:
        store: CA

    mount:
        baked:
