version: "0.1"

x-real-ip: &real-ip
    real-ip:
        from:
            - 10.0.0.0/8 # AWS VPC network
            - 103.21.244.0/22 # Cloudflare
            - 103.22.200.0/22 # Cloudflare
            - 103.31.4.0/22 # Cloudflare
            - 104.16.0.0/12 # Cloudflare
            - 108.162.192.0/18 # Cloudflare
            - 131.0.72.0/22 # Cloudflare
            - 141.101.64.0/18 # Cloudflare
            - 162.158.0.0/15 # Cloudflare
            - 172.64.0.0/13 # Cloudflare
            - 173.245.48.0/20 # Cloudflare
            - 188.114.96.0/20 # Cloudflare
            - 190.93.240.0/20 # Cloudflare
            - 197.234.240.0/22 # Cloudflare
            - 198.41.128.0/17 # Cloudflare
            - 2400:cb00::/32 # Cloudflare
            - 2606:4700::/32 # Cloudflare
            - 2803:f800::/32 # Cloudflare
            - 2405:b500::/32 # Cloudflare
            - 2405:8100::/32 # Cloudflare
            - 2c0f:f248::/32 # Cloudflare
            - 2a06:98c0::/29 # Cloudflare

x-frontend-auth: &frontend-auth
    <<: *real-ip
    auth:
        engine: basic
        users:
            -   username: cloud
                password: cloud
        exclude:
            - '${ALLOWED_IP}' # AWS gateway
            - 185.60.20.0/24 # PayOne

namespace: spryker-cloud
tag: '1.0'

environment: docker.demo
image:
    tag: spryker/php:7.3-alpine3.12
    environment:
        SPRYKER_CLUSTER: "apac"
        SPRYKER_DEFAULT_STORE: "MY"
        SPRYKER_ACTIVE_STORES: "MY,HK,AU,NZ,PH,TH,MO"
        SPRYKER_HOOK_BEFORE_DEPLOY: "vendor/bin/install -r apac/pre-deploy -vvv"
        SPRYKER_HOOK_AFTER_DEPLOY: "true"
        SPRYKER_HOOK_INSTALL: "vendor/bin/install -r apac/production --no-ansi -vvv"
        SPRYKER_HOOK_DESTRUCTIVE_INSTALL: "vendor/bin/install -r apac/destructive-stag --no-ansi -vvv"
        WEB_PROPERTY_ID: "GTM-53PNGR9"
    php:
        ini:
            "post_max_size": 1024M
            "upload_max_filesize": 1024M
            "opcache.enable_cli": 1
            "apc.enable_cli": 1
        enabled-extensions:
            - blackfire
            - newrelic

composer:
    mode: --no-dev
    autoload: --classmap-authoritative

assets:
    image: fholzer/nginx-brotli:v1.18.0
    mode: production
    compression:
        brotli:
            static: only
        gzip:
            static: true
            level: 5

regions:
    apac:
        services:
            database:
                database: myworld_staging-apac
                username: spryker
                password: secret

        stores:
            MY:
                services:
                    broker:
                        namespace: my_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: my_search
                    session:
                        namespace: 1
            HK:
                services:
                    broker:
                        namespace: hk_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: hk_search
                    session:
                        namespace: 1
            AU:
                services:
                    broker:
                        namespace: au_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: au_search
                    session:
                        namespace: 1
            NZ:
                services:
                    broker:
                        namespace: nz_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: nz_search
                    session:
                        namespace: 1
            PH:
                services:
                    broker:
                        namespace: ph_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: ph_search
                    session:
                        namespace: 1
            TH:
                services:
                    broker:
                        namespace: th_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: th_search
                    session:
                        namespace: 1
            MO:
                services:
                    broker:
                        namespace: mo_queue
                    key_value_store:
                        namespace: 1
                    search:
                        namespace: mo_search
                    session:
                        namespace: 1

groups:
    apac:
        region: apac
        applications:
            Redirects:
                application: static
                endpoints:
                    my.myworld-mca.cloud.spryker.toys:
                        store: MY
                        redirect:
                            type: 302
                            url: www.my.myworld-mca.cloud.spryker.toys
                    hk.myworld-mca.cloud.spryker.toys:
                        store: HK
                        redirect:
                            type: 302
                            url: www.hk.myworld-mca.cloud.spryker.toys
                    au.myworld-mca.cloud.spryker.toys:
                        store: AU
                        redirect:
                            type: 302
                            url: www.au.myworld-mca.cloud.spryker.toys
                    nz.myworld-mca.cloud.spryker.toys:
                        store: NZ
                        redirect:
                            type: 302
                            url: www.nz.myworld-mca.cloud.spryker.toys
                    ph.myworld-mca.cloud.spryker.toys:
                        store: PH
                        redirect:
                            type: 302
                            url: www.ph.myworld-mca.cloud.spryker.toys
                    th.myworld-mca.cloud.spryker.toys:
                        store: TH
                        redirect:
                            type: 302
                            url: www.th.myworld-mca.cloud.spryker.toys
                    mo.myworld-mca.cloud.spryker.toys:
                        store: MO
                        redirect:
                            type: 302
                            url: www.mo.myworld-mca.cloud.spryker.toys
            Yves:
                application: yves
                endpoints:
                    www.my.myworld-mca.cloud.spryker.toys:
                        store: MY
                        <<: *frontend-auth
                    www.hk.myworld-mca.cloud.spryker.toys:
                        store: HK
                        <<: *frontend-auth
                    www.au.myworld-mca.cloud.spryker.toys:
                        store: AU
                        <<: *frontend-auth
                    www.nz.myworld-mca.cloud.spryker.toys:
                        store: NZ
                        <<: *frontend-auth
                   www.ph.myworld-mca.cloud.spryker.toys:
                        store: PH
                        <<: *frontend-auth
                   www.th.myworld-mca.cloud.spryker.toys:
                        store: TH
                        <<: *frontend-auth
                   www.mo.myworld-mca.cloud.spryker.toys:
                        store: MO
                        <<: *frontend-auth
            Zed:
                application: zed
                http:
                    max-request-body-size: 1600m
                endpoints:
                    zed.my.myworld-mca.cloud.spryker.toys:
                        store: MY
                        <<: *frontend-auth
                    zed.hk.myworld-mca.cloud.spryker.toys:
                        store: HK
                        <<: *frontend-auth
                    zed.au.myworld-mca.cloud.spryker.toys:
                        store: AU
                        <<: *frontend-auth
                    zed.nz.myworld-mca.cloud.spryker.toys:
                        store: NZ
                        <<: *frontend-auth
                    zed.ph.myworld-mca.cloud.spryker.toys:
                        store: PH
                        <<: *frontend-auth
                    zed.th.myworld-mca.cloud.spryker.toys:
                        store: TH
                        <<: *frontend-auth
                    zed.mo.myworld-mca.cloud.spryker.toys:
                        store: MO
                        <<: *frontend-auth
            Glue:
                application: glue
                endpoints:
                    glue.my.myworld-mca.cloud.spryker.toys:
                        store: MY
                    glue.hk.myworld-mca.cloud.spryker.toys:
                        store: HK
                    glue.au.myworld-mca.cloud.spryker.toys:
                        store: AU
                    glue.nz.myworld-mca.cloud.spryker.toys:
                        store: NZ
                    glue.ph.myworld-mca.cloud.spryker.toys:
                        store: PH
                    glue.th.myworld-mca.cloud.spryker.toys:
                        store: TH
                    glue.mo.myworld-mca.cloud.spryker.toys:
                        store: MO

services:
    database:
        engine: mysql
        version: mariadb-10.5
        root:
            username: "root"
            password: "secret"
        endpoints:
            localhost:5432:
                protocol: tcp
    broker:
        engine: rabbitmq
        api:
            username: "spryker"
            password: "secret"
        endpoints:
            rabbitmq.myworld-mca-apac.cloud.spryker.toys:
            localhost:5672:
                protocol: tcp
    session:
        engine: redis
    key_value_store:
        engine: redis
        endpoints:
            localhost:16379:
                protocol: tcp
    search:
        engine: elastic
        version: 6.8
        endpoints:
            localhost:9200:
                protocol: tcp
    scheduler:
        engine: jenkins
        endpoints:
            jenkins.myworld-mca-apac.cloud.spryker.toys:
    mail_catcher:
        engine: mailhog
        endpoints:
            mail.myworld-mca-apac.cloud.spryker.toys:

docker:

    blackfire:
        enabled: true

    ssl:
        enabled: true
        redirect: true

    debug:
        enabled: false
        xdebug:
            enabled: false

    testing:
        store: MY

    mount:
        baked:
